apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    app: test-service
spec:
  ports:
    - name: http
      port: 8000
  selector:
    app: test-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test-service
        version: v1
    spec:
      containers:
        - name: test-app
          image: gcr.io/aqueous-cargo-232709/gke-test
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5