apiVersion: v1
kind: Service
metadata:
  name: gke-test
  labels:
    app: gke-test
spec:
  ports:
    - type: LoadBalancer
    - name: http
      port: 8080
  selector:
    app: gke-test
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gke-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gke-test
        version: v1
    spec:
      containers:
        - name: test-app
          image: gcr.io/aqueous-cargo-232709/gke-test
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 5