apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: test-service # match images with this name
    newTag: 1.8.0 # override the tag
    newName: test-service-special # override the name
resources:
  - deployment.yaml